#!/usr/bin/perl

# CLI Pipe Viewer - configuration file
# Managed by Home Manager

use utf8;

our $CONFIG = {
  api_host                      => "auto",
  audio_quality                 => "best",
  auto_captions                 => 0,
  autoplay_mode                 => 0,
  cache_dir                     => "$ENV{HOME}/.cache/pipe-viewer",
  colors                        => 1,
  confirm                       => 0,
  download_with_wget            => 1,
  download_with_ytdl            => 1,
  downloads_dir                 => ".",
  get_captions                  => 1,
  get_subscriptions_in_parallel => 1,
  get_term_width                => 1,
  history                       => 1,
  interactive                   => 1,
  maxResults                    => 20,
  order                         => "upload_date",
  resolution                    => "best",
  subscription_results          => "uploads",
  update_config                 => 0,
  video_player_selected         => "vlc",
  video_players                 => {
    mpv => {
      arg => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*",
      audio => "--audio-file=*AUDIO*",
      cmd => "mpv",
      fs => "--fullscreen",
      novideo => "--no-video",
      srt => "--sub-file=*SUB*",
    },
    vlc => {
      arg => "--quiet --play-and-exit --no-video-title-show --input-title-format=*TITLE* *VIDEO*",
      audio => "--input-slave=*AUDIO*",
      cmd => "vlc",
      fs => "--fullscreen",
      novideo => "--intf=dummy --novideo",
      srt => "--sub-file=*SUB*",
    },
  },
  ytdl                          => 1,
  ytdl_cmd                      => "yt-dlp",
}
